name: validate-sources

on:
  push

jobs:
  xmllint:
    name: Run xmllint --valid
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python version
        uses: actions/setup-python@v3.0.0
        with:
          python-version: '3.12'
      - name: Install xmllint
        run: |
          sudo apt-get install -y --no-install-recommends xmllint
      - name: Run xmllint
        run:
          ls src/*.xml | xargs python .githooks/pre-commit-xmllint-validate.py
